version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: ims-admin
      POSTGRES_DB: ims-db
    ports:
      - 5499:5432
    volumes:
      - psql_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./:/var/www/html
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 8903:8903
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    environment:
      - DATABASE_URL=postgresql://ims-admin:password@db:5432/ims-db?schema=public
volumes:
  psql_data:
